indent_style = "Block"
use_small_heuristics = "Max"
comment_width = 100
condense_wildcard_suffixes = true
control_brace_style = "ClosingNextLine"
format_strings = true
hard_tabs = true
imports_layout = "HorizontalVertical"
merge_imports = true
max_width = 100
merge_derives = true
force_multiline_blocks = true
newline_style = "Unix"
normalize_comments = true
reorder_imports = true
reorder_modules = true
reorder_impl_items = true
space_after_colon = true
trailing_comma = "Vertical"
trailing_semicolon = true
type_punctuation_density = "Wide"
use_field_init_shorthand = false
format_code_in_doc_comments = true
wrap_comments = true
